#!/bin/bash

# First, install the extension manager
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build

# Rebuild (with the lowest memory options)
jupyter lab build --dev-build=False --minimize=False